"""
FraudShield data loader.

Load order:
  1. IEEE-CIS Fraud Detection dataset (real, if present at data_dir)
  2. Synthetic wallet fraud dataset    (auto-generated, at data_dir)

Synthetic dataset is generated by training/generate_synthetic_data.py and
stored at backend/data/synthetic_wallet_fraud.parquet.  It uses ONLY the
wallet-native features available at inference time, eliminating the
train/inference mismatch that caused weak ML signals when training on
V-features that were median-imputed at wallet inference.

Expected files for IEEE-CIS mode (download from Kaggle):
  - train_transaction.csv   (required)
  - train_identity.csv      (optional, merged when present)
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd


# ---------------------------------------------------------------------------
# IEEE-CIS loader (original, unchanged)
# ---------------------------------------------------------------------------

def load_ieee_cis(data_dir: str) -> pd.DataFrame:
    """
    Load the IEEE-CIS Fraud Detection dataset.

    Parameters
    ----------
    data_dir : str
        Directory containing train_transaction.csv and optionally
        train_identity.csv.

    Returns
    -------
    pd.DataFrame
        Merged dataframe indexed by integer position (TransactionID dropped).
    """
    data_path = Path(data_dir)
    tx_path   = data_path / "train_transaction.csv"
    id_path   = data_path / "train_identity.csv"

    if not tx_path.exists():
        raise FileNotFoundError(
            f"train_transaction.csv not found in '{data_dir}'.\n"
            "Download the IEEE-CIS Fraud Detection dataset from:\n"
            "  https://www.kaggle.com/c/ieee-fraud-detection/data"
        )

    print(f"[DataLoader] Loading {tx_path} ...")
    df_tx = pd.read_csv(tx_path)
    print(f"[DataLoader] Transactions loaded: {len(df_tx):,} rows, {df_tx.shape[1]} columns")

    if id_path.exists():
        print(f"[DataLoader] Loading identity data from {id_path} ...")
        df_id = pd.read_csv(id_path)
        print(f"[DataLoader] Identity data: {len(df_id):,} rows, {df_id.shape[1]} columns")
        df = df_tx.merge(df_id, on="TransactionID", how="left")
        print(f"[DataLoader] Merged shape: {df.shape}")
    else:
        print("[DataLoader] train_identity.csv not found — proceeding without identity features.")
        df = df_tx.copy()

    if "TransactionID" in df.columns:
        df = df.drop(columns=["TransactionID"])

    df = df.reset_index(drop=True)

    fraud_rate = df["isFraud"].mean() if "isFraud" in df.columns else float("nan")
    mem_mb     = df.memory_usage(deep=True).sum() / 1_048_576
    print(f"[DataLoader] Final shape  : {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"[DataLoader] Fraud rate   : {fraud_rate:.4%}")
    print(f"[DataLoader] Memory usage : {mem_mb:.1f} MB")

    return df


# ---------------------------------------------------------------------------
# Synthetic loader
# ---------------------------------------------------------------------------

def load_synthetic(data_dir: str) -> pd.DataFrame:
    """
    Load the pre-generated synthetic wallet fraud dataset.

    The dataset lives at data_dir/synthetic_wallet_fraud.parquet (.parquet
    preferred for speed; .csv accepted as fallback).

    If neither file exists, auto-generates using the default parameters and
    saves to data_dir so subsequent runs are instant.
    """
    data_path    = Path(data_dir)
    parquet_path = data_path / "synthetic_wallet_fraud.parquet"
    csv_path     = data_path / "synthetic_wallet_fraud.csv"

    if parquet_path.exists():
        print(f"[DataLoader] Loading synthetic data from {parquet_path} ...")
        df = pd.read_parquet(parquet_path)
    elif csv_path.exists():
        print(f"[DataLoader] Loading synthetic data from {csv_path} ...")
        df = pd.read_csv(csv_path)
    else:
        print("[DataLoader] Synthetic dataset not found — auto-generating (this runs once) ...")
        _auto_generate(data_path)
        df = pd.read_parquet(parquet_path)

    fraud_rate = df["isFraud"].mean() if "isFraud" in df.columns else float("nan")
    print(f"[DataLoader] Synthetic data: {len(df):,} rows, fraud rate={fraud_rate:.4%}")
    return df


def _auto_generate(data_path: Path) -> None:
    """Run the synthetic generator and save the dataset."""
    import sys
    training_dir = Path(__file__).resolve().parent
    if str(training_dir) not in sys.path:
        sys.path.insert(0, str(training_dir))

    from generate_synthetic_data import generate

    data_path.mkdir(parents=True, exist_ok=True)
    df = generate(n_total=250_000, fraud_rate=0.035, seed=42)
    # Try parquet first; fall back to CSV if pyarrow/fastparquet not installed
    out = data_path / "synthetic_wallet_fraud.parquet"
    try:
        df.to_parquet(out, index=False)
    except ImportError:
        out = data_path / "synthetic_wallet_fraud.csv"
        df.to_csv(out, index=False)
    print(f"[DataLoader] Synthetic dataset saved to {out}  ({out.stat().st_size / 1_048_576:.1f} MB)")


# ---------------------------------------------------------------------------
# Unified loader — tries IEEE-CIS first, falls back to synthetic
# ---------------------------------------------------------------------------

def load_dataset(data_dir: str) -> pd.DataFrame:
    """
    Load training data.

    Priority:
      1. IEEE-CIS (train_transaction.csv found in data_dir)
         → uses full IEEE-CIS feature set; pass wallet_only=True to train_engine
            so only wallet-native features are selected for training.
      2. Synthetic wallet dataset
         → already in wallet-native feature space; works with wallet_only=True.

    Returns
    -------
    pd.DataFrame with at minimum: TransactionAmt, TransactionDT, isFraud
    """
    data_path = Path(data_dir)
    ieee_path = data_path / "train_transaction.csv"

    if ieee_path.exists():
        print(f"[DataLoader] Found IEEE-CIS dataset at {ieee_path} — using real data.")
        return load_ieee_cis(data_dir)

    print("[DataLoader] IEEE-CIS not found — using synthetic wallet fraud dataset.")
    return load_synthetic(data_dir)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_dataset(df: pd.DataFrame) -> bool:
    """
    Validate that a DataFrame is suitable for FraudShield training.

    Accepts both IEEE-CIS and synthetic wallet formats.
    """
    required = {"TransactionAmt", "isFraud", "TransactionDT"}
    missing  = required - set(df.columns)
    if missing:
        print(f"[DataLoader] Validation FAILED — missing columns: {missing}")
        return False

    fraud_rate = df["isFraud"].mean()
    if not (0.005 <= fraud_rate <= 0.20):
        print(
            f"[DataLoader] Validation FAILED — fraud rate {fraud_rate:.4%} "
            "is outside the expected 0.5–20% range."
        )
        return False

    print(f"[DataLoader] Validation PASSED — {len(df):,} rows, fraud rate {fraud_rate:.4%}")
    return True
